version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-174-129-225-160.compute-1.amazonaws.com
            port: '5432'
            database: ddn8mca7dvu6fq
            ssl: true
            user: vxvoaxfclazjyo
            password: 4ab3f9002ed312ce53228a973166799dd374c68dddaf9fb4c1db84d6a398286b
            migrations: true